import os
import cv2
from tqdm import tqdm

def resize_with_padding(image, target_size=640):    # target_size es el tamaño final deseado (640x640)
    """
    Cambia el tamaño de la imagen manteniendo la relación de aspecto original
    y añade bordes negros (padding) para alcanzar el tamaño objetivo de forma simétrica.
    """
    h, w = image.shape[:2]
    scale = target_size / max(h, w)
    new_w, new_h = int(w * scale), int(h * scale)
    
    # Redimensionar manteniendo proporciones
    resized = cv2.resize(image, (new_w, new_h), interpolation=cv2.INTER_AREA)
    
    # Crear un lienzo negro del tamaño objetivo
    # OpenCV usa el formato (Alto, Ancho, Canales de color)
    channels = image.shape[2] if len(image.shape) == 3 else 1
    padded_image = cv2.copyMakeBorder(
        resized,
        top=(target_size - new_h) // 2,
        bottom=target_size - new_h - (target_size - new_h) // 2,
        left=(target_size - new_w) // 2,
        right=target_size - new_w - (target_size - new_w) // 2,
        borderType=cv2.BORDER_CONSTANT,
        value=[0] * channels
    )
    return padded_image

def preprocess_dataset(raw_dir, processed_dir, target_size=640):
    """
    Recorre el directorio de imágenes originales, valida, limpia, estandariza y renombra.
    """
    # Crear carpeta de destino si no existe
    os.makedirs(processed_dir, exist_ok=True)
    
    # Extensiones de imagen soportadas
    valid_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')
    image_files = [f for f in os.listdir(raw_dir) if f.lower().endswith(valid_extensions)]
    
    print(f"📌 Se encontraron {len(image_files)} imágenes para procesar.")
    
    success_count = 0
    # tqdm genera una barra de progreso profesional en la terminal
    for index, filename in enumerate(tqdm(image_files, desc="Procesando imágenes")):
        raw_path = os.path.join(raw_dir, filename)
        
        try:
            # 1. Intentar leer la imagen con OpenCV
            img = cv2.imread(raw_path)
            
            # Validar si el archivo está corrupto o no es legible
            if img is None:
                print(f"\n⚠️ Advertencia: No se pudo leer {filename}. Posible archivo corrupto. Saltando...")
                continue
                
            # 2. Aplicar el escalado profesional con padding
            processed_img = resize_with_padding(img, target_size)
            
            # 3. Formatear el nombre secuencial limpio (ej: auto_001.jpg)
            new_filename = f"auto_{str(index + 1).zfill(3)}.jpg"
            processed_path = os.path.join(processed_dir, new_filename)
            
            # 4. Guardar la imagen final estandarizada
            cv2.imwrite(processed_path, processed_img)
            success_count += 1
            
        except Exception as e:
            print(f"\n❌ Error inesperado al procesar {filename}: {str(e)}")
            
    print(f"\n🎉 ¡Proceso completado con éxito! {success_count}/{len(image_files)} imágenes guardadas en '{processed_dir}'.")

if __name__ == "__main__":

    # Arquitectura de carpetas:
#   │
#   ├── data/
#   │   ├── raw/               # Fotos originales de vehículos sin procesar
#   │   └── processed/         # Imágenes recortadas o normalizadas mediante
#   │   │
#   │   └── dataset/             # 📂 PLACE UNZIPPED ROBOFLOW CONTENTS HERE
#   │       ├── train/           # 70% of images and .txt label files
#   │       ├── valid/           # 20% of images and .txt label files
#   │       ├── test/            # 10% of images and .txt label files
#   │       └── data.yaml        # 📄 Configuration file generated by Roboflow
#   │
#   ├── runs/                   # Directorio para almacenar los resultados del entrenamiento
#   │   └── detect/             #
#   │       └── plate_detector/          #
#   │           └── weights/             #
#   │
#   │
#   ├── notebooks/             # Análisis y pruebas
#   │
#   ├── scripts/               
#   │   └── data_preprocessing.py
#   │   └── train_detector.py
#   │
#   ├── requirements.txt       # Librerías necesarias
#   └── README.md              # Documentación del proyecto


    # Encuentra la ubicación exacta de este archivo (scripts/data_preprocessing.py)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Se mueve un nivel arriba para llegar a la raíz del proyecto
    project_root = os.path.abspath(os.path.join(script_dir, ".."))
    
    # Definición de rutas absolutas correctas
    RAW_DATA_DIR = os.path.join(project_root, "data", "raw")
    PROCESSED_DATA_DIR = os.path.join(project_root, "data", "processed")
    
    preprocess_dataset(RAW_DATA_DIR, PROCESSED_DATA_DIR, target_size=640)
